name: Proyecto integrador - Actualización de datos y documentación

# Se ejecuta cuando haces push o pull request a la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Añadir esta sección de permisos
permissions:
  contents: write

# Configura el ambiente y los jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checa el código en el repositorio
    - name: Check out repository
      uses: actions/checkout@v3

    # Configura Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Instala las dependencias del proyecto
    - name: Instalar dependencias
      run: pip install -e .
    
    # Corre el script de main
    - name: Ejecutar Script de main
      run: python src/recoleccion_de_datos_automaticos/main.py

    # Commit y push de los archivos generados
    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git add logs/
        git add src/recoleccion_de_datos_automaticos/static/data/riot_data.csv
        git commit -m "Actualizar archivos de logs, auditoria y csv [skip ci]" || echo "No changes to commit"
        git push
    

