name: Proyecto integrador - Actualización de datos y documentación

# Se ejecuta cuando haces push o pull request a la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Añadir esta sección de permisos
permissions:
  contents: write

# Configura el ambiente y los jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checa el código en el repositorio
    - name: Check out repository
      uses: actions/checkout@v3

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Instala las dependencias del proyecto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    # Corre el script de logger.py
    - name: Run Logger script
      run: |
        python src/recoleccion_de_datos_automaticos/main.py

